# Generated by Django 2.1.4 on 2019-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typefood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typefood_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='order_text',
            new_name='menu_text',
        ),
    ]
