# Generated by Django 2.1.4 on 2019-02-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20190215_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='typefood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typefood', to='foodapp.Typefood'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='foodapp.Restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewres', to='foodapp.Restaurant'),
        ),
    ]
