# Generated by Django 2.1.4 on 2019-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_auto_20190223_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='place_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
