# Generated by Django 2.1.4 on 2019-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_restaurant_place_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='time_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
